# Generated by Django 5.2.4 on 2025-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, default='+966', max_length=5, null=True, verbose_name='مفتاح الدولة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user_temp', max_length=150, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
