"""
Django settings for BruBox project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# -------------------------------------------------------------
# المسار الأساسي للمشروع
# -------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------
# مفتاح الأمان (⚠️ غيّره في بيئة الإنتاج)
# -------------------------------------------------------------
SECRET_KEY = 'django-insecure-h&b+8%28wa#@3&*0w9o3*1wim8rl&h8b)n!(4@s(2sv&d_=$)^'

# -------------------------------------------------------------
# وضع التصحيح (فعّل False في الإنتاج)
# -------------------------------------------------------------
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# -------------------------------------------------------------
# التطبيقات المثبتة
# -------------------------------------------------------------
INSTALLED_APPS = [
    # تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # تطبيقات المشروع
    'core',
    'products',
    'orders',
]

# -------------------------------------------------------------
# الوسيطات (Middlewares)
# -------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -------------------------------------------------------------
# إعدادات التوجيه (URL routing)
# -------------------------------------------------------------
ROOT_URLCONF = 'BruBox.urls'

# -------------------------------------------------------------
# إعدادات القوالب (Templates)
# -------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مجلد القوالب العام
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # ضروري لتسجيل الدخول
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -------------------------------------------------------------
# إعدادات WSGI
# -------------------------------------------------------------
WSGI_APPLICATION = 'BruBox.wsgi.application'

# -------------------------------------------------------------
# إعدادات قاعدة البيانات
# -------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------------------------------------
# تحقق كلمات المرور
# -------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------------
# اللغة والمنطقة الزمنية
# -------------------------------------------------------------
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -------------------------------------------------------------
# الملفات الثابتة (Static Files)
# -------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# -------------------------------------------------------------
# إعداد ملفات الوسائط (Media)
# -------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------
# نوع الحقول الافتراضي للموديلات
# -------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------
# إعادة التوجيه بعد تسجيل الدخول
# -------------------------------------------------------------
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
